#
# PRの作成者をアサインする
#
---

name: Assign author to PR

on:
  pull_request:
    types: [ opened ]

jobs:
  assign:
    if: github.actor != 'dependabot[bot]' || github.actor != 'renovate[bot]'
    name: Assign author
    runs-on: ubuntu-latest
    steps:
      - name: PR 作成者にアサインする
        uses: technote-space/assign-author@v1
